# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastation_sales', models.CharField(max_length=100)),
                ('plastation_expenses', models.CharField(max_length=100)),
                ('xbox_sales', models.CharField(max_length=100)),
                ('xbox_expenses', models.CharField(max_length=100)),
                ('accessory_sales', models.CharField(max_length=100)),
                ('accessory_expenses', models.CharField(max_length=100)),
                ('total_sales', models.CharField(max_length=100)),
                ('total_expenses', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
