# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f39e93fdf561f1cce3095fb83a548d8dd5fd9a24ebe9abecea28aee28620b0a3bdc207d070aaa93b969df05757a912fe02173e6950e2dfb03e2f33242b83f76

test:
  secret_key_base: 5374e236e5dd4585b48832cdf82a38491e8a963bc36512fbf40c7d0f4b89694d346d813fb1e722ffccabcf37d70214013e28833ae113fafddf743047800edc87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
