# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20170223_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='', null=True),
        ),
    ]
