# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4736bab78bd8ee2be232563092bd4a703c70d6885e9c0280337a63fe0f93f1fa269652df6043059974c728ce4ad491e09dc33b2ba67ad19b406e8beb8c45b9b

test:
  secret_key_base: ac71363cd0096a4e6f16c736d22646b87104dadea795256157e7e5a2d298abba90d8fbf8415f00d7748a8dc1ec3ef595b8d25ee3c5bb87a8b0bc4b2232f01a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
